<?php

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
大会サイト、ローカル、テスト、本番とterm IDが違うため
各種設定のlocation valueを変数に書き換え
'acf_top-visual' > $topvisualId
'acf_entry-button' > $entrybuttonId
'acf_pickup-topics' > $pickuptopicsId
'acf_map-init' > $mapinitId
'acf_important' > $importantId
'acf_partner' > $partnerId
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
// echo $entrybuttonId . ':' . $pickuptopicsId . ':' . $mapinitId . ':' . $importantId;


if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_top-setting',
		'title' => 'top setting',
		'fields' => array (
			array (
				'key' => 'field_5742c50a54717',
				'label' => 'ビジュアルセット',
				'name' => 'visual_set',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5742c55254718',
						'label' => '画像PC',
						'name' => 'visual_set_img',
						'type' => 'image',
						'instructions' => '1,440px × 610px',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5742c58f54719',
						'label' => '画像スマホ',
						'name' => 'visual_set_imgsp',
						'type' => 'image',
						'instructions' => '750px × 700px',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5742c5ba5471a',
						'label' => 'リンク先',
						'name' => 'visual_set_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5742c5f65471b',
						'label' => 'ターゲット',
						'name' => 'visual_set_target',
						'type' => 'true_false',
						'instructions' => 'リンク先を別ウィンドウで開きたい場合はチェックしてください。',
						'column_width' => '',
						'message' => '別ウィンドウ',
						'default_value' => 0,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
			array (
				'key' => 'field_5840dbda62508',
				'label' => 'リンクボタン',
				'name' => 'top_links',
				'type' => 'repeater',
				'instructions' => '|	1	|	2	|<br>|	3	|	4	|<br>|	5	|	6	|<br>|	7	|	8	|<br>の順です。',
				'sub_fields' => array (
					array (
						'key' => 'field_5840dc7c62509',
						'label' => 'テキスト',
						'name' => 'top_linksText',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5840dc936250a',
						'label' => 'アイコン',
						'name' => 'top_linksIcon',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'carte.svg' => '書類',
							'stopwatch.svg' => 'ストップウォッチ',
							'guest.svg' => '人物',
							'event.svg' => '旗',
							'medal.svg' => 'メダル',
							'prize.svg' => 'トロフィー',
							'car.svg' => '車',
							'clock.svg' => '時計',
							'bike.svg' => '自転車',
							'bed.svg' => 'ベッド',
							'drink.svg' => 'ドリンク',
							'star.svg' => '星',
							'heart.svg' => 'ハート',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_5840dcbd6250b',
						'label' => 'リンク先',
						'name' => 'top_linksUrl',
						'type' => 'text',
						'instructions' => 'URLを入力してください。',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5840dce66250c',
						'label' => '強調',
						'name' => 'top_linksEmph',
						'type' => 'true_false',
						'instructions' => '参加案内書のように目立たせたい場合はチェックしてください。',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					//保留　2017.06
					// array (
					// 	'key' => 'field_591d0aac26538',
					// 	'label' => '別ウィンドウ',
					// 	'name' => 'top_linksBlank',
					// 	'type' => 'true_false',
					// 	'column_width' => '',
					// 	'message' => '',
					// 	'default_value' => 0,
					// ),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
			array (
				'key' => 'field_5779cc6606623',
				'label' => '地域情報リンク',
				'name' => 'visual_localLink',
				'type' => 'repeater',
				'instructions' => 'トップページ地域情報箇所に表示されるテキストリンクです。',
				'sub_fields' => array (
					array (
						'key' => 'field_5779ccb306624',
						'label' => 'テキスト',
						'name' => 'visual_localLink_text',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5779ccc706625',
						'label' => 'URL',
						'name' => 'visual_localLink_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5779cce806626',
						'label' => '別ウィンドウ',
						'name' => 'visual_localLink_target',
						'type' => 'true_false',
						'instructions' => '同一ウィンドウで開きたい場合はチェックを外してください。',
						'column_width' => '',
						'message' => '',
						'default_value' => 1,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
			array (
				'key' => 'field_5779cbe806622',
				'label' => '【2017以降使用しない】TOPICS表示件数',
				'name' => 'visual_topicsNum',
				'type' => 'radio',
				'instructions' => 'トップページに表示するトピックスの件数を設定します。',
				'choices' => array (
					4 => '4件',
					8 => '8件',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 4,
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => $topvisualId,
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));




	register_field_group(array (
		'id' => 'acf_overview',
		'title' => 'overview',
		'fields' => array (
			array (
				'key' => 'field_5732b6ad9026f',
				'label' => '大会の特徴',
				'name' => 'overview_feature',
				'type' => 'wp_wysiwyg',
				'default_value' => '',
				'teeny' => 0,
				'media_buttons' => 1,
				'dfw' => 1,
			),
			array (
				'key' => 'field_5731a1500241c',
				'label' => 'テーブル',
				'name' => 'overview_tableSet',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5731a18c0241d',
						'label' => '項目',
						'name' => 'overview_tableSet_item',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731a1a20241e',
						'label' => '内容',
						'name' => 'overview_tableSet_contents',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'html',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
			array (
				'key' => 'field_5742cb47f3dcc',
				'label' => 'スケジュール',
				'name' => 'overview_scheduleSet',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5742cb74f3dcf',
						'label' => 'タイトル',
						'name' => 'overview_scheduleSet_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5742d03c94c5c',
						'label' => 'ID',
						'name' => 'overview_scheduleSet_id',
						'type' => 'text',
						'instructions' => 'アンカーでリンクする場合に必要になります。 anchor_○○（半角英数）',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5742cc27f3dd0',
						'label' => '時間セット',
						'name' => 'overview_scheduleset_time',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5742cc7df3dd1',
								'label' => '時間',
								'name' => 'overview_scheduleset_time_time',
								'type' => 'text',
								'instructions' => '時間帯記入例：7:30&lt;br&gt;｜&lt;br&gt;8:30',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5742ccdbf3dd2',
								'label' => '内容',
								'name' => 'overview_scheduleset_time_contents',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => 1,
								'formatting' => 'br',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => '追加',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-overview.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => -1,
	));
	register_field_group(array (
		'id' => 'acf_attend-after',
		'title' => 'attend after',
		'fields' => array (
			array (
				'key' => 'field_591d1389cabee',
				'label' => '写真',
				'name' => 'attend_photo',
				'type' => 'image',
				'instructions' => 'width:800px height:任意',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-after.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => -1,
	));
	register_field_group(array (
		'id' => 'acf_attend',
		'title' => 'attend',
		'fields' => array (
			array (
				'key' => 'field_57306e2ef18cb',
				'label' => '項目',
				'name' => 'attend_itemSet',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_573070a06f5c2',
						'label' => 'タイトル',
						'name' => 'attend_itemSet_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_573081fced491',
						'label' => 'ID',
						'name' => 'attend_itemSet_id',
						'type' => 'text',
						'instructions' => 'アンカーリンク用ID。<br>anchor_○○（半角英数）',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'anchor_',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_573070bc6f5c3',
						'label' => '説明文',
						'name' => 'attend_itemSet_description',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'html',
					),
					array (
						'key' => 'field_573070e76f5c4',
						'label' => 'リンクボタン',
						'name' => 'attend_itemSet_linkSet',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_573071436f5c7',
								'label' => 'ボタンテキスト',
								'name' => 'attend_itemSet_linkSet_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5730712c6f5c6',
								'label' => 'PDF',
								'name' => 'attend_itemSet_linkSet_pdf',
								'type' => 'file',
								'column_width' => '',
								'save_format' => 'object',
								'library' => 'all',
							),
							array (
								'key' => 'field_57343c04c5096',
								'label' => 'URL',
								'name' => 'attend_itemSet_linkSet_url',
								'type' => 'text',
								'instructions' => 'PDFではなくページへリンクしたい場合はこちらにURLを入力してください。',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => '追加',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-beforeafter.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-after.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'revisions',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contents-set',
		'title' => 'contents set',
		'fields' => array (
			array (
				'key' => 'field_57319e993b0c3',
				'label' => 'コンテンツセット',
				'name' => 'contents_set',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_57319ebe3b0c4',
						'label' => 'タイトル',
						'name' => 'contents_set_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57319ee13b0c5',
						'label' => 'ID',
						'name' => 'contents_set_id',
						'type' => 'text',
						'instructions' => 'アンカーでリンクする場合に必要になります。<br>anchor_○○（半角英数）',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'anchor_',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731a0507cb7b',
						'label' => '内容',
						'name' => 'contents_set_contents',
						'type' => 'wp_wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'teeny' => 0,
						'media_buttons' => 1,
						'dfw' => 1,
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-overview.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-recruit.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-course.php',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_entry-button',
		'title' => 'entry button',
		'fields' => array (
			array (
				'key' => 'field_5732bc03eb743',
				'label' => 'エントリーリンク先',
				'name' => 'entry_link',
				'type' => 'text',
				'instructions' => 'エントリーボタンのリンク先を設定してください。<br>
	空欄の場合はボタンは表示されません。',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5742c908809c9',
				'label' => 'エントリーキャプション',
				'name' => 'entry_caption',
				'type' => 'text',
				'instructions' => 'ナビゲーション「エントリー」に表示されるキャプションです。<br>簡潔に。例）受付中！~3/10',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5ceb3e582a249',
				'label' => '参加者の方へリンク先',
				'name' => 'entry_attendlink',
				'type' => 'text',
				'instructions' => '参加者の方へのリンク先を設定してください。<br>
	空欄の場合はボタンは表示されません。<br>',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5cac1141737d9',
				'label' => '参加案内キャプション',
				'name' => 'entry_attendcaption',
				'type' => 'text',
				'instructions' => 'ナビゲーション「参加案内」に表示されるキャプションです。<br>簡潔に。例）参加者の方へ',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => $entrybuttonId,
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_important',
		'title' => 'important',
		'fields' => array (
			array (
				'key' => 'field_57331b00078db',
				'label' => 'お知らせ内容',
				'name' => 'important_text',
				'type' => 'wysiwyg',
				'instructions' => '空欄の場合は表示されません。',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => $importantId,
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_local',
		'title' => 'local',
		'fields' => array (
			array (
				'key' => 'field_573c38637950f',
				'label' => '本文中写真',
				'name' => 'local_contentsPhoto',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_573c38e179510',
				'label' => '本文',
				'name' => 'local_contentsText',
				'type' => 'wp_wysiwyg',
				'default_value' => '',
				'teeny' => 0,
				'media_buttons' => 1,
				'dfw' => 1,
			),
			array (
				'key' => 'field_573bc5cbd1eec',
				'label' => '位置情報',
				'name' => 'local_point',
				'type' => 'google_map',
				'instructions' => '住所入力してください。<br>ピンをドラッグ＆ドロップで微調整できます。',
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
			array (
				'key' => 'field_5726d000f5d52',
				'label' => 'サムネイル',
				'name' => '',
				'type' => 'message',
				'instructions' => '480px × 285px 【jpg形式】',
				'message' => '<span style="font-size:110%">サムネイルを右上の「アイキャッチ画像」から登録してください。480px × 285px 【jpg形式】</span>',
			),
			array (
				'key' => 'field_5726d12563dbe',
				'label' => 'マーカー画像',
				'name' => 'local_marker',
				'type' => 'text',
				'instructions' => '生成された画像パスが自動で入ります。<span style="color:red">※編集不要です。</span>',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'local',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_localcat',
		'title' => 'localcat',
		'fields' => array (
			array (
				'key' => 'field_5726cf10b97b6',
				'label' => 'アイコン',
				'name' => 'localcat_icon',
				'type' => 'image',
				'instructions' => '180px × 180px<br>
	未登録の場合は/series/images/marker/icon_スラッグ名のファイルを使用します。',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'localcat',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_map-init',
		'title' => 'map init',
		'fields' => array (
			array (
				'key' => 'field_573c42188268b',
				'label' => '中心',
				'name' => 'map_center',
				'type' => 'google_map',
				'instructions' => '住所を入力してください。マーカーをドラッグ＆ドロップで位置を微調整できます。',
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
			array (
				'key' => 'field_573c423b8268c',
				'label' => 'zoom',
				'name' => 'map_zoom',
				'type' => 'select',
				'instructions' => '地図の縮尺です。',
				'choices' => array (
					11 => 11,
					12 => 12,
					13 => 13,
					14 => 14,
					15 => 15,
					16 => 16,
				),
				'default_value' => 14,
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => $mapinitId,
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_news',
		'title' => 'news',
		'fields' => array (
			array (
				'key' => 'field_57329c7887112',
				'label' => '本文',
				'name' => 'news_text',
				'type' => 'wysiwyg',
				'instructions' => 'HTMLタグが利用可能です。',
				'toolbar' => 'full',
				'media_upload' => 'yes',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'news',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_pickup-topics',
		'title' => 'pickup topics',
		'fields' => array (
			array (
				'key' => 'field_57316214b9576',
				'label' => '【2017以降使用しない】注目記事',
				'name' => 'pickup_topics',
				'type' => 'relationship',
				'instructions' => 'ピックアップしたい記事を左から選んでください。<br>選択した記事はドラッグ＆ドロップで並び替えられます。',
				'return_format' => 'id',
				'post_type' => array (
					0 => 'topics',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_57345c1acf4da',
				'label' => 'はじめての方へ記事',
				'name' => 'pickup_beginner',
				'type' => 'relationship',
				'instructions' => 'ピックアップしたい記事を左から選んでください。<br>選択した記事はドラッグ＆ドロップで並び替えられます。',
				'return_format' => 'id',
				'post_type' => array (
					0 => 'topics',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => $pickuptopicsId,
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_topics',
		'title' => 'topics',
		'fields' => array (
			array (
				'key' => 'field_5731523835e89',
				'label' => 'アイキャッチ',
				'name' => 'topics_eyecatch',
				'type' => 'image',
				'instructions' => '480px × 285px',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_57635003207f8',
				'label' => 'リード文',
				'name' => 'topics_read',
				'type' => 'textarea',
				'instructions' => '一覧ページで表示される文章です。40文字程度が目安です。',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_5731aa111ec4e',
				'label' => 'コンテンツセット',
				'name' => 'topics_set',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5c943f0bd85a7',
						'label' => '大見出し',
						'name' => 'topics_set_headline',
						'type' => 'text',
						'instructions' => '2019.03追加',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731aa271ec4f',
						'label' => 'タイトル',
						'name' => 'topics_set_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731aa421ec50',
						'label' => '画像',
						'name' => 'topics_set_img',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5731aac91ec51',
						'label' => '本文',
						'name' => 'topics_set_contents',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
			array (
				'key' => 'field_5cabf7d0869af',
				'label' => '外部リンク',
				'name' => 'topics_link',
				'type' => 'text',
				'instructions' => '外部ページへリンクしたい場合はURLを入力してください。',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'topics',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_partner',
		'title' => 'partner',
		'fields' => array (
			array (
				'key' => 'field_5742e1532cc7d',
				'label' => 'パートナーセット',
				'name' => 'partner_set',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5742e1732cc7e',
						'label' => 'ロゴ',
						'name' => 'partner_set_logo',
						'type' => 'image',
						'instructions' => '220px × 130px',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5742e1962cc7f',
						'label' => 'リンク先',
						'name' => 'partner_set_link',
						'type' => 'text',
						'instructions' => 'URLを記入してください。',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => $partnerId,
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));


	register_field_group(array (
		'id' => 'acf_faq',
		'title' => 'faq',
		'fields' => array (
			array (
				'key' => 'field_57591e7380a6c',
				'label' => 'カテゴリー',
				'name' => 'faq_category',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_57591e8e80a6d',
						'label' => 'カテゴリタイトル',
						'name' => 'faq_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57592dff3ec63',
						'label' => 'Q&A',
						'name' => 'faq_qanda',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_57592e163ec64',
								'label' => '質問',
								'name' => 'faq_question',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_57592e2c3ec65',
								'label' => '答え',
								'name' => 'faq_answer',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'html',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => '追加',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-faq.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));

	register_field_group(array (
		'id' => 'acf_entry',
		'title' => 'entry',
		'fields' => array (
			array (
				'key' => 'field_5763b474a3f4b',
				'label' => 'FAX用紙',
				'name' => 'entry_fax',
				'type' => 'file',
				'save_format' => 'object',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-entry.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));


	register_field_group(array (
		'id' => 'acf_otherpage',
		'title' => 'otherpage',
		'fields' => array (
			array (
				'key' => 'field_5850f12b7801e',
				'label' => 'コンテンツセット',
				'name' => 'otherpage_set',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5c9443cb8693d',
						'label' => '大見出し',
						'name' => 'otherpage_set_headline',
						'type' => 'text',
						'instructions' => '2019.03追加',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5850f1407801f',
						'label' => 'タイトル',
						'name' => 'otherpage_set_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5850f15d78020',
						'label' => '画像',
						'name' => 'otherpage_set_img',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5850f17f78021',
						'label' => '本文',
						'name' => 'otherpage_set_contents',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => '追加',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page/page-other.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));

}

?>
